//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Leilao
    {
        public int IdLeilao { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public Nullable<System.DateTime> DataFechamento { get; set; }
        public string NomeProduto { get; set; }
        public string DescricaoProduto { get; set; }
        public Nullable<decimal> ValorInicial { get; set; }
        public Nullable<decimal> ValorVendido { get; set; }
        public Nullable<bool> Usado { get; set; }
    }
}
